const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const crypto=require('node:crypto');const {PokerGame}=require('./game-engine');
const PORT=Number(process.env.PORT||4173),rooms=new Map(),root=path.join(__dirname,'public');
const json=(res,code,data)=>{res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
const body=req=>new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1e6)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})});
const id=()=>crypto.randomBytes(12).toString('base64url'),code=()=>String(crypto.randomInt(100000,1000000));
function find(roomCode,token){const room=rooms.get(roomCode);if(!room)throw Error('房间不存在');const player=room.tokens.get(token);if(!player)throw Error('身份已失效，请重新加入');return{room,player};}
function addBot(room,n){const names=['小北','阿岚','老K','米娅','七仔','凯文','安娜','乔伊','山姆'];for(let i=0;i<n;i++)room.game.addPlayer({id:id(),name:names[room.game.players.filter(p=>p.isBot).length]||`电脑${i+1}`,isBot:true,avatar:crypto.randomInt(1,7)});}
function scheduleNextHand(room){if(room.nextHandTimer||room.game.status!=='finished')return;const live=room.game.players.filter(p=>p.chips>0);if(live.length<=1){room.nextHandAt=null;return;}room.nextHandAt=Date.now()+4000;room.nextHandTimer=setTimeout(()=>{room.nextHandTimer=null;room.nextHandAt=null;if(room.game.status!=='finished')return;room.game.startHand();scheduleBot(room)},4000);}
function scheduleBot(room){if(room.botTimer||room.game.status!=='playing'||room.game.turn<0)return;const p=room.game.players[room.game.turn];if(!p?.isBot)return;const expectedId=p.id;room.botTimer=setTimeout(()=>{room.botTimer=null;if(room.game.status!=='playing'||room.game.players[room.game.turn]?.id!==expectedId)return scheduleBot(room);const l=room.game.legal(expectedId);if(!l)return scheduleBot(room);let type=l.check?'check':'call',amount=0;const strength=Math.random();if(l.raise&&strength>.78){type='raise';amount=Math.min(l.maxRaiseTo,l.minRaiseTo+room.game.bigBlind*crypto.randomInt(0,4));}else if(l.fold&&strength<.16)type='fold';room.game.action(expectedId,type,amount);scheduleNextHand(room);scheduleBot(room)},crypto.randomInt(1000,2001));}
function apiError(res,e){json(res,400,{error:e.message||'请求失败'});}
const server=http.createServer(async(req,res)=>{try{
  const u=new URL(req.url,'http://local');
  if(req.method==='POST'&&u.pathname==='/api/rooms'){const b=await body(req),roomCode=code(),token=id(),pid=id(),targetSeats=Math.max(2,Math.min(10,Number(b.targetSeats)||4)),game=new PokerGame({...(b.settings||{}),initialChips:Math.max(500,Math.min(1000000,Number(b.initialChips)||5000))});game.addPlayer({id:pid,name:b.name,avatar:b.avatar});const room={code:roomCode,game,targetSeats,owner:pid,tokens:new Map([[token,pid]]),created:Date.now()};if(b.mode==='solo')addBot(room,targetSeats-1);rooms.set(roomCode,room);return json(res,200,{room:roomCode,token,playerId:pid});}
  if(req.method==='POST'&&/^\/api\/rooms\/\d{6}\/join$/.test(u.pathname)){const roomCode=u.pathname.split('/')[3],room=rooms.get(roomCode);if(!room)throw Error('找不到这个房间');if(room.game.players.length>=room.targetSeats)throw Error('房间人数已满');const b=await body(req),token=id(),pid=id();room.game.addPlayer({id:pid,name:b.name,avatar:b.avatar});room.tokens.set(token,pid);return json(res,200,{room:roomCode,token,playerId:pid});}
  if(req.method==='GET'&&/^\/api\/rooms\/\d{6}$/.test(u.pathname)){const roomCode=u.pathname.split('/')[3],{room,player}=find(roomCode,u.searchParams.get('token')),live=room.game.players.filter(p=>p.chips>0).length;return json(res,200,{...room.game.view(player,roomCode),targetSeats:room.targetSeats,isOwner:room.owner===player,nextHandAt:room.nextHandAt||null,tournamentFinished:room.game.status==='finished'&&live<=1});}
  if(req.method==='POST'&&/^\/api\/rooms\/\d{6}\/start$/.test(u.pathname)){const roomCode=u.pathname.split('/')[3],b=await body(req),{room,player}=find(roomCode,b.token),live=room.game.players.filter(p=>p.chips>0).length;if(room.game.status==='finished'&&live<=1){clearTimeout(room.nextHandTimer);room.nextHandTimer=null;room.nextHandAt=null;room.game.resetTournament();room.game.startHand();scheduleBot(room);return json(res,200,{ok:true,restarted:true});}if(room.owner!==player)throw Error('只有房主可以开始牌局');if(room.game.status!=='waiting')throw Error('下一局将自动开始');if(room.game.players.length<room.targetSeats)addBot(room,room.targetSeats-room.game.players.length);room.game.startHand();scheduleBot(room);return json(res,200,{ok:true});}
  if(req.method==='POST'&&/^\/api\/rooms\/\d{6}\/action$/.test(u.pathname)){const roomCode=u.pathname.split('/')[3],b=await body(req),{room,player}=find(roomCode,b.token);room.game.action(player,b.type,b.amount);scheduleNextHand(room);scheduleBot(room);return json(res,200,{ok:true});}
  let file=u.pathname==='/'?'index.html':u.pathname.slice(1);file=path.normalize(file).replace(/^(\.\.[/\\])+/, '');const full=path.join(root,file);if(!full.startsWith(root)||!fs.existsSync(full)||fs.statSync(full).isDirectory()){res.writeHead(404);return res.end('Not found');}const ext=path.extname(full),types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(full).pipe(res);
}catch(e){apiError(res,e)}});
server.listen(PORT,'0.0.0.0',()=>{const ips=Object.values(os.networkInterfaces()).flat().filter(x=>x.family==='IPv4'&&!x.internal).map(x=>`http://${x.address}:${PORT}`);console.log(`\n德州猫猫酒馆已启动\n本机：http://localhost:${PORT}\n手机：${ips.join(' 或 ')||'请查看局域网地址'}\n`)});
setInterval(()=>{for(const[k,r]of rooms)if(Date.now()-r.created>12*3600e3)rooms.delete(k)},3600e3).unref();
